fix: streamline COPR build push logic

diff --git a/.github/workflows/copr-build.yml b/.github/workflows/copr-build.yml
--- a/.github/workflows/copr-build.yml
+++ b/.github/workflows/copr-build.yml
@@ -172,7 +172,7 @@ jobs:
             echo -e "${COLOR_SUCCESS}==> [SUCCESS] $APP is already up to date.${COLOR_RESET}"
           fi
 
-      - name: Bump Version and Push
+      - name: Bump Version and Commit Changes
         if: steps.check.outputs.update_needed == 'true'
         env:
           PROVIDER: "${{ matrix.provider }}"
@@ -261,6 +261,27 @@ jobs:
           git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
           git add "$SPEC" "$README"
           git commit -m "chore($APP): bump version to $NEW_VER"
+
+      - name: Trigger COPR Build
+        if: steps.check.outputs.update_needed == 'true'
+        env:
+          APP: ${{ matrix.app_name }}
+          COPR_URL: ${{ secrets.COPR_BASE_WEBHOOK_URL }}
+        run: |
+          BASE_URL=$(echo "$COPR_URL" | xargs)
+          FINAL_URL="${BASE_URL%/}/$APP/"
+
+          echo -e "${COLOR_INFO}==> [INFO] Triggering COPR build...${COLOR_RESET}"
+          if curl -fsS -X POST "$FINAL_URL"; then
+            echo -e "${COLOR_SUCCESS}==> [SUCCESS] Triggered COPR build!${COLOR_RESET}"
+          else
+            echo "::error::==> [ERROR] Webhook failed to trigger COPR build."
+            exit 1
+          fi
+
+      - name: Push Changes to GitHub
+        if: steps.check.outputs.update_needed == 'true'
+        run: |
           MAX_RETRIES=5
           for i in $(seq 1 $MAX_RETRIES); do
             echo -e "${COLOR_INFO}==> [INFO] Push attempt $i...${COLOR_RESET}"
@@ -275,25 +296,8 @@ jobs:
             sleep $(( (RANDOM % 10) + 1 ))
           done
 
-      - name: Trigger COPR Build
-        id: copr-trigger
-        if: steps.check.outputs.update_needed == 'true'
-        env:
-          APP: ${{ matrix.app_name }}
-          COPR_URL: ${{ secrets.COPR_BASE_WEBHOOK_URL }}
-        run: |
-          FINAL_URL="$COPR_URL/$APP/"
-
-          echo -e "${COLOR_INFO}==> [INFO] Triggering COPR build...${COLOR_RESET}"
-          if curl -fsS -X POST "$FINAL_URL"; then
-            echo -e "${COLOR_SUCCESS}==> [SUCCESS] Triggered COPR build!${COLOR_RESET}"
-          else
-            echo "::error::==> [ERROR] Webhook failed to trigger COPR build."
-            exit 1
-          fi
-
       - name: Add to Workflow Summary
-        if: steps.copr-trigger.outcome == 'success'
+        if: steps.check.outputs.update_needed == 'true'
         env:
           APP: ${{ matrix.app_name }}
         run: |
